### ISSUE TITLE
Wouldn't it be good to add a feature in your program to execute the BWA program directly?

### ISSUE THREAD

**Issue by HamidMushtaq** [citiususc/SparkBWA#46]
I tried to compile and use SparkBWA, but was having a lot of problems with that JNI thing. Since, I wanted to test it with BWA mem, I changed the run function, so that instead of using JNI, I execute the bwa mem program directly. The BWA excutable is sent to the worker nodes with the --files option of spark-submit.  I used ProcessBuilder with redirectOutput to run the BWA program and save its output to a file. 

I have two questions. Firstly, is executing bwa mem through ProcessBuilder slower than using JNI to call it? Secondly, what are other advantages of using JNI instead of directly running the BWA executable? I am showing my modifications below.

I would suggest that you should add an option in your program to run the BWA executable directly.

```
public int run(int alnStep) 
{
	// Get the list of arguments passed by the user
	String[] parametersArray = parseParameters(alnStep);
        String[] y = parametersArray[parametersArray.length-1].split("RDD");
	String y1 = y[y.length-1];
	String id = y1.split("_")[0];
			
	// Call to JNI with the selected parameters
	/*int returnCode = BwaJni.Bwa_Jni(parametersArray);

	if (returnCode != 0) {
		LOG.error("["+this.getClass().getName()+
"] :: BWA exited with error code: " + String.valueOf(returnCode));
		log("run/" + id, "["+this.getClass().getName()+
"] :: BWA exited with error code: " + String.valueOf(returnCode));
		return returnCode;
	}*/
	try
	{
                String runParams[] = {"./bwa", "mem", "-t", "-4", 
parametersArray[6], parametersArray[7], parametersArray[8]};
	        
		Process proc = new ProcessBuilder(runParams).redirectOutput(
new File(parametersArray[5])).start();
		proc.waitFor();
		log("run/" + id, "bwa sucessfully finished!");
		return 0;
	}
	catch (Exception e) 
	{
		log("run/" + id, "Error in processing this chunk! " + e.getMessage());
		return 1;
	}
}
```

**Comment by jmabuin** [comment]
In my experience performance should be pretty similar, with the only overhead of calling a new process. However, in my opinion, JNI is a better choice because of the following reasons:

- You may infer into a **timeout**. The process that is actually consuming a lot of CPU is external to Spark, YARN or Mesos. The process that the cluster manager is launching is not doing anything but waiting, so the cluster manager can kill it because of the timeout configuration setting. This happened to us when trying Halvade.

- An improvement to the current approach can be to call only the bwa functions that actually works in the alignment, not to the whole, bwa function (that is, actually, our current goal). I mean, the reads are read by Spark and you have them distributed into a RDD. Then you call only the aligner and get the result. You have the input read and the resulting alignment in memory and you can use it for the next phase if you want, **everything** in memory. If you launch an external process you always have to use the disk, while with JNI this approach is possible.

**Comment by HamidMushtaq** [comment]
I see. But the timeout can be set in the program. I was also having timeout problems when I tried Halvade, but then I added the following to prevent timeouts -> config.setLong("mapreduce.task.timeout", reallyBigTimeInMillisecs); Similar thing can be done in Spark. Your second point is valid indeed though.

**Comment by jmabuin** [comment]
Yes, but you need to know approximately that time previously. 

We also set that option with Halvade in order to execute large jobs
